apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chatbot-data-pvc
  namespace: default
  labels:
    app: chatbot-todo-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
